disabled_rules:
 - colon
 - comma
 - control_statement
 - trailing_whitespace
included:
 - ChargeFlix
excluded:
 - Carthage
 - Pods
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
 min_length: # only min_length
    error: 4 # only error
 excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
