# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChargeFlix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChargeFlix
  pod 'Kingfisher', '~> 7.0'

  target 'ChargeFlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChargeFlixUITests' do
    # Pods for testing
  end

end
